/*
    Author Name : Neha Agrawal
    Date : 22/4/2016
    Name : Queueable Apex class that inserts the same Contact for each Account for a specific state
*/
    public class AddPrimaryContact implements Queueable
    {
        private Contact c;
        private String state;
        public  AddPrimaryContact(Contact c, String state)    {
            this.c = c;
            this.state = state;
        }    
        public void execute(QueueableContext context) {
            List<Account> ListAccount = [SELECT ID, Name ,(Select id,FirstName,LastName from contacts ) FROM ACCOUNT WHERE BillingState = :state LIMIT 200];
            List<Contact> lstContact = new List<Contact>();
            for (Account acc:ListAccount){
                Contact cont = c.clone(false,false,false,false);
                cont.AccountId =  acc.id;
                lstContact.add( cont );
             }
             if(lstContact.size() >0 ){
                 insert lstContact;
             }   
        }
}